################################################
#
# Analysis script for PINK1 data set in MADS course
#
# by C. AMeli and A. Skupin 2023/10 with updates 2025/11
#
################################################

# ================================= LIBRARIES ==================================

library(Seurat)
library(dplyr)
library(tidyverse)
library(viridisLite)
library(viridis)
library(ggplot2)
library(openxlsx)
library(slingshot)


# the final object was generated by filtering for days and conditions from the full object:
#S_input = readRDS(file = '/Users/alexander.skupin/projects/papers_to_do/Michi_Pink1_differentiation/SC_Analysis/Michela_Transcriptomics_R/sc_analysis_pink1/SeuratFinal.rds')

#redset <- c("WT_57","WT_37" , "WT_18" , "WT_25" ,  "WT_0"   , "ND_37" ,  "ND_57"  , "ND_18" , "ND_25" ,  "ND_0")
redset2 <- c("WT_57","WT_37" ,  "WT_0"   , "ND_37" ,  "ND_57"    ,  "ND_0")

#S_red = subset(S_input, ConditionDay %in% redset2)
#unique(S_red$ConditionDay)
#saveRDS(S_red,paste("./SeuratFinal_red.rds",sep=""))

# to get clean environment
rm(list = ls())


# ================================ PARAMETERS ==================================

# set your working directory accordingly
setwd('/Users/alexander.skupin/projects/teaching/WS2025/MADS/project1')

input_file = "./SeuratFinal.rds"
output_folder = "./Results/"

#to export things later
writeExcel = TRUE

# = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = 
#                             ---- RELABELING ----                  
# = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = 

# Load mapped data-sets

S = readRDS(input_file)

summary(S)
dim(S)
head(colnames(S))
tail(colnames(S))
head(colnames(S))
head(rownames(S))

head(S[[]])

Assays(S)


# Convert meta-data to factors

S$Day = factor(S$Day, levels = c(0,18,25,37,57))
S$Condition = str_replace_all(S$Condition, "ND","PINK1")
S$Condition = str_replace_all(S$Condition,"WT","CTL")
S$ConditionDay = paste(S$Condition,S$Day,sep = " ")

S$ConditionDay = factor(S$ConditionDay, levels = c("CTL 0","PINK1 0",
                                                   "CTL 18","PINK1 18",
                                                   "CTL 25","PINK1 25",
                                                   "CTL 37","PINK1 37",
                                                   "CTL 57","PINK1 57"))

S$ConditionDay = factor(S$ConditionDay, levels = c("CTL 0","CTL 18","CTL 25","CTL 37","CTL 57",
                                                   "PINK1 0","PINK1 18","PINK1 25","PINK1 37","PINK1 57"))

S$Condition = factor(S$Condition, levels = c("CTL","PINK1"))

# now you can have a look into the object ... summary, dim, head etc ...

## to get that scaled data in 
expression_matrix <- GetAssayData(S, slot = "scale.data")


tempa <- subset(S, ConditionDay %in% "CTL 0")
expression_matrix_CTL_0 <- GetAssayData(tempa, slot = "scale.data")




# do we have already PCA information? 

FeaturePlot(S, features="nCount_RNA")
FeaturePlot(S, features="nCount_RNA",split.by='Day')
DimPlot(S, split.by='Day')

ElbowPlot(S,ndims = 30)

DimHeatmap(S, dims = 1:9, cells = 1000, balanced = TRUE)

######## new Dim reduction since the current is based on full data set

# if u run into memory issues - u can also put everything into S instead of S_new

S_new = ScaleData(S)
S_new = RunPCA(S_new,npcs = 100)

ElbowPlot(S_new,ndims = 30)
DimHeatmap(S_new, dims = 1:9, cells = 1000, balanced = TRUE)

# here u should play around with dims, n.neigbors check also ?RunUMAP - something for reduction=? ; what happens for other assays?
set.seed(18)
S_new = RunUMAP(S_new ,dims = 1:100,assay = "integrated",n.neighbors = 50, seed.use = NULL)

# We can store different parameter set in the object by defining reduction.name = "nameofreduction" -default is "umap"

DimPlot(object = S_new, reduction = "umap")
DimPlot(object = S_new, reduction = "umap", group.by = "Condition", split.by = "Day",shuffle = TRUE) 
DimPlot(object = S_new, reduction = "umap", group.by = "Day", split.by = "Condition",shuffle = TRUE) 


# = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = 
#                   ---- NORMALIZING ASSAYS BEFORE DEGs ----                  
# = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = 

S = NormalizeData(S,assay = "RNA")
S = NormalizeData(S,assay = "RNA_imputed")



# = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = 
#                            ---- DEGs DAYWISE ----                  
# = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = 

DefaultAssay(S) = "RNA" # for the different Assays
S = SetIdent(object = S, value = S$ConditionDay)

for(pink in c("PINK1")){
  for(day in c(0,18,25,37,57)) {
    print(paste(pink,day))
    temp = FindMarkers(S, 
                       assay = "RNA", 
                       ident.1 = paste("CTL",day,sep=" "), 
                       ident.2 = paste(pink,day,sep=" "),
                       logfc.threshold = 0.25,
                       min.pct = 0.05,
                       densify = TRUE,
                       test.use = "MAST",
                       latent.vars = "nFeature_RNA",
                       slot = "data")
    temp$Day = day
    temp$Gene = rownames(temp)
    temp$ident.1 = "CTL"
    temp$ident.2 = pink
    rownames(temp) = paste(pink,day,c(1:dim(temp)[1]),sep="_")
    if(day==0 & pink == "PINK1"){
      DEG = temp
    }else{
      DEG = rbind(DEG,temp)
    }
  }
}

DEG = DEG %>% 
  select(Gene,Day,pct.1,pct.2,avg_log2FC,p_val,p_val_adj,ident.1,ident.2)  %>%
  arrange(Day,Gene,ident.2)

# Export

if(writeExcel){
  write.xlsx(DEG,paste(output_folder,"DEG_DETAILED_MADS.xlsx",sep=""),colNames = TRUE,rowNames = FALSE)
}

# Test the effect of the corresponding Assay
DefaultAssay(S) = "RNA_imputed"
#DefaultAssay(S) = "RNA"

FeaturePlot(S,features=c("ABHD13", "VIM", "TH"))

# = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = 
#                            ---- CLUSTERING ----                  
# = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = 

DefaultAssay(S) = "integrated"

# play with the following functions - remember: https://satijalab.org/seurat/articles/pbmc3k_tutorial.html

# ?FindNeighbors
S_new = FindNeighbors(S_new, reduction = "pca", dims = 1:10)
S_new = FindClusters(S_new, resolution = 0.4)

DimPlot(S_new)
# to map clusters to sampels - have to check for gene profiles
#S$seurat_clusters = factor(S$seurat_clusters, levels = c(10,11,3,7,5,6,4,2,9,0,1,8,12,13,14))

# = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = 
#                       ---- PLOTS TRANSCRIPTOMICS ----                  
#                       Condition WT vs ND - Day 0 to 57              
# = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = 

# ----  Umap plots  ---- 

###check here what yo can already do

pdf(paste(output_folder,"/UMAP_plots.pdf",sep=''),width = 10,height = 10)

print(
  DimPlot(object = S, reduction = "umap", group.by = "Day",shuffle = TRUE,
          label = TRUE, label.size = 5,label.box = TRUE,repel=TRUE) + 
    theme_minimal() +ggplot2::theme(legend.position = "none") +
    theme_minimal() +
    theme(legend.position = "none") +
    labs(x = "UMAP 1", y = "UMAP 2", title = "Umap by Day") +
    theme(plot.title = element_text(hjust = 0.5))
)
print(
  DimPlot(object = S, reduction = "umap", group.by = "Condition",shuffle = TRUE,
          label = TRUE, label.size = 5,label.box = TRUE,repel=TRUE) + 
    theme_minimal() +ggplot2::theme(legend.position = "none") +
    theme_minimal() +
    theme(legend.position = "none") +
    labs(x = "UMAP 1", y = "UMAP 2", title = "Umap by Condition") +
    theme(plot.title = element_text(hjust = 0.5))
)
print(
  DimPlot(object = S, reduction = "umap", group.by = "ConditionDay",shuffle = TRUE,
          label = TRUE, label.size = 5,label.box = TRUE,repel=TRUE) + 
    theme_minimal() +ggplot2::theme(legend.position = "none") +
    theme_minimal() +
    theme(legend.position = "none") +
    labs(x = "UMAP 1", y = "UMAP 2", title = "Umap by Condition and Day") +
    theme(plot.title = element_text(hjust = 0.5))
)
print(
  DimPlot(object = S, reduction = "umap", group.by = "seurat_clusters",label = TRUE,shuffle = TRUE,
          label.size = 5,label.box = TRUE,repel=TRUE) + 
    theme_minimal() +ggplot2::theme(legend.position = "none") +
    theme_minimal() +
    theme(legend.position = "none") +
    labs(x = "UMAP 1", y = "UMAP 2", title = "Umap by Cluster") +
    theme(plot.title = element_text(hjust = 0.5)) + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())
)

dev.off()

DimPlot(object = S, reduction = "umap", group.by = "Day",shuffle = TRUE, split.by = "Condition",label = FALSE, label.size = 5,label.box = TRUE,repel=TRUE) + 
  theme_minimal() +
  labs(x = "UMAP 1", y = "UMAP 2", title = "Umap by Day of Differentiation") +
  theme(plot.title = element_text(hjust = 0.5)) + 
 # scale_fill_manual( values = rep(DayColors,1)) + 
  #scale_colour_manual( values = rep(DayColors,1)) +
  theme(axis.line = element_line(color='black'),
        plot.background = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_blank())

DimPlot(object = S, reduction = "umap", group.by = "seurat_clusters",label = TRUE,shuffle = TRUE,
        label.size = 3,label.box = TRUE,repel=FALSE) + 
  theme_minimal() +
  theme(legend.position = "none") +
  labs(x = "UMAP 1", y = "UMAP 2", title = "Umap by Clusters") +
  scale_fill_manual( values = ClusterColors) + 
  scale_colour_manual( values = ClusterColors) +
  theme(axis.line = element_line(color='black'),
        plot.background = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_blank())



# ---- Differentiation markers dot-plot ----

gene_complete = c("POU5F1","L1TD1","TDGF1","OTX2","SOX2","FOXA2","LMX1A","WNT5A","DDC","ASCL1","NR4A2","DCX","PBX1")

S = SetIdent(S,value = "Condition")

pdf(paste(output_folder,"/DifferentiationMarkers_WT.pdf",sep=''),width = 12,height = 3)
DotPlot(S, 
        features = gene_complete,
        assay = "RNA_imputed",
        group.by = "Day", 
        dot.scale = 5, 
        cols = c("white", "black"),  
        scale.min = 0,
        scale.max = 1, 
        col.min = 0,
        col.max = 1)
dev.off()

pdf(paste(output_folder,"/DifferentiationMarkers_ND.pdf",sep=''),width = 12,height = 3)
pinkset <- c( "PINK1 37" ,  "PINK1 57"  , "PINK1 18" , "PINK1 25" ,  "PINK1 0")

DotPlot(subset(S,ConditionDay %in% pinkset), 
        features = gene_complete,
        assay = "RNA_imputed",
        group.by = "Day", 
        dot.scale = 5, 
        cols = c("white", "black"),  
        scale.min = 0,
        scale.max = 1, 
        col.min = 0,
        col.max = 1)
dev.off()

# ---- Differentiation markers heatmap ----

DefaultAssay(S) = "RNA_imputed"
S = ScaleData(S,assay = "RNA_imputed")
S = SetIdent(object = S, value = S$ConditionDay)

DoHeatmap(S,features = c("MYC","POU5F1","L1TD1","TDGF1","POLR3G","TERF1","FABP7","FOXA2","OTX2","SOX2","SOX6","WNT5A","LMX1A","ASCL1","DDC","NR4A2","DCX","PBX1","KCNJ6"),
          slot = "scale.data", draw.lines = FALSE,raster= FALSE) + scale_fill_viridis()




############## for DEG Vulcano plots

volc = ggplot(DEG, aes(- avg_log2FC, -log(p_val_adj))) +
  geom_point(color="grey", size=1) #+
 # geom_point(data = DEG[vec_gene_down,],aes(- avg_log2FC, -log(p_val_adj)), color="red") + 
  #geom_point(data = DEG[vec_gene_up,],aes(- avg_log2FC, -log(p_val_adj)), color="blue") 

volc + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), axis.line = element_line(colour = "black"))


# For pathway and processes analysis 

# This should be done daywise and cluster wise adressing the questions:

# what are Pathways, Molecular functions and Cellular components that chenge over time and between conditions

# GO Term enrichment using 
library(gprofiler2)

#get a list of downregulated genes and then run GO enrichment

ranked_genes_fc <- setNames( DEG$avg_log2FC, DEG$Gene) #  remember - how is FC defined in DEG: FC = log(cond1/cond2)
ranked_genes_fc <- sort(ranked_genes_fc, decreasing = TRUE)

gene_down <- names(ranked_genes_fc) # down in PINK1 means up in CTL: FC = CTL/PINK1
gost_res_down <- gost(gene_down, 
                      organism = "hsapiens", # Specify organism (hsapiens = human)
                      ordered_query = FALSE, 
                      significant = TRUE, 
                      user_threshold = 0.05, # FDR threshold for significance
                      correction_method = "fdr") # Multiple testing correction method


# View the results
#head(gost_res_down$result)

gostplot(gost_res_down, capped = TRUE, interactive = TRUE)

top_pathways_down <- gost_res_down$result[order(gost_res_down$result$p_value), ][1:20, ]


ggplot(top_pathways_down, aes(x = reorder(term_name, -p_value), y = -log10(p_value))) +
  geom_point(aes(size = intersection_size, color = -log10(p_value))) +  # Size based on number of DEGs in the pathway
  scale_color_gradient(low = "blue", high = "red") +  # Color gradient based on p-value
  theme_minimal() +
  coord_flip() +  # Flip coordinates for better readability
  labs(title = "Top 20 Enriched Pathways", 
       x = "Pathway", 
       y = "-log10(p-value)", 
       size = "Gene Count", 
       color = "-log10(p-value)") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))


#here you can then look/plot also into other / lower ranks by changing the numbers in the [] like for 21:40
top_pathways_down_2 <- gost_res_down$result[order(gost_res_down$result$p_value), ][21:40, ]


ggplot(top_pathways_down_2, aes(x = reorder(term_name, -p_value), y = -log10(p_value))) +
  geom_point(aes(size = intersection_size, color = -log10(p_value))) +  # Size based on number of DEGs in the pathway
  scale_color_gradient(low = "blue", high = "red") +  # Color gradient based on p-value
  theme_minimal() +
  coord_flip() +  # Flip coordinates for better readability
  labs(title = "Top 21:40 Enriched Pathways", 
       x = "Pathway", 
       y = "-log10(p-value)", 
       size = "Gene Count", 
       color = "-log10(p-value)") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))


# you can also make your specific list by defining an index vector
go_select <- c( 23:25, 31, 40)
top_pathways_down_sel <- gost_res_down$result[order(gost_res_down$result$p_value), ][go_select, ]

ggplot(top_pathways_down_sel, aes(x = reorder(term_name, -p_value), y = -log10(p_value))) +
  geom_point(aes(size = intersection_size, color = -log10(p_value))) +  # Size based on number of DEGs in the pathway
  scale_color_gradient(low = "blue", high = "red") +  # Color gradient based on p-value
  theme_minimal() +
  coord_flip() +  # Flip coordinates for better readability
  labs(title = "Top 21:40 Enriched Pathways", 
       x = "Pathway", 
       y = "-log10(p-value)", 
       size = "Gene Count", 
       color = "-log10(p-value)") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

# TO export the resukts and screen through pathways:
#install.packages("openxlsx")

library(openxlsx)
toexport <- gost_res_down$result
write.xlsx(toexport, file = "gprofiler_go_results_down.xlsx")

# bar plots for significance (again you can select the pathways you want to show by defining the variable top_pathways_down - see above):
ggplot(top_pathways_down, aes(x = reorder(term_name, -p_value), y = -log10(p_value))) +
  geom_bar(stat = "identity", fill = "steelblue") +
  coord_flip() +  # Flip the coordinates for better readability
  theme_minimal() +
  labs(title = "Top 20 Enriched Pathways by Significance", 
       x = "Pathway", 
       y = "-log10(p-value)") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

######## NOW You can do this for upregulated genes ... and filter this per day etc ...


#### Next is GSEA which is a more robust way to get the involved mechanisms

# 2. with clusterProfiler by Gene Set Enrichment Analysis (GSEA)
# install packages with Biomanager like: 

#if (!require("BiocManager", quietly = TRUE))
#install.packages("BiocManager")
#BiocManager::install("org.Hs.eg.db")

library(clusterProfiler)
library(org.Hs.eg.db)
#library(enrichplot)

# to generate sorted vector based on FC - 
# could be also done by days by exchanging mada with mada_30 or mada_42 respectively
# intersting to do - also to get rid of warning of duplicated gene names?

ranked_genes_fc <- setNames( DEG$avg_log2FC, DEG$Gene) #  remember - how is FC defined in DEG
ranked_genes_fc <- sort(ranked_genes_fc, decreasing = TRUE)

ranked_genes_fc_down <- setNames( DEG$avg_log2FC, DEG$Gene) # again 
ranked_genes_fc_down <- sort(ranked_genes_fc_down, decreasing = TRUE)

ranked_genes_fc_up <- setNames(- DEG$avg_log2FC, DEG$Gene) # again 
ranked_genes_fc_up <- sort(ranked_genes_fc_up, decreasing = TRUE)

# and here you can also change BP to CC and MF - see description
gsea_fc_down <- gseGO(
  geneList = ranked_genes_fc_down,           # Ranked gene list
  OrgDb = org.Hs.eg.db,              # Organism annotation database (human)
  keyType = "SYMBOL",                # Gene identifier type (e.g., SYMBOL, ENTREZID)
  ont = "CC",                        # Ontology type (BP = Biological Process, MF = Molecular Function, CC = Cellular Component)
  minGSSize = 10,                    # Minimum gene set size for testing
  maxGSSize = 500,                   # Maximum gene set size for testing
  pvalueCutoff = 0.05,               # p-value threshold for significance
  verbose = FALSE                    # Suppress verbose output
)

dotplot(gsea_fc_down, showCategory = 10) +
  ggtitle("Top Enriched for Down regulated genes")

gsea_fc_up <- gseGO(
  geneList = ranked_genes_fc_up,           # Ranked gene list
  OrgDb = org.Hs.eg.db,              # Organism annotation database (human)
  keyType = "SYMBOL",                # Gene identifier type (e.g., SYMBOL, ENTREZID)
  ont = "CC",                        # Ontology type (BP = Biological Process, MF = Molecular Function, CC = Cellular Component)
  minGSSize = 10,                    # Minimum gene set size for testing
  maxGSSize = 500,                   # Maximum gene set size for testing
  pvalueCutoff = 0.05,               # p-value threshold for significance
  verbose = FALSE                    # Suppress verbose output
)

dotplot(gsea_fc_up, showCategory = 20) +
  ggtitle("Top Enriched for UP regulated genes")


# to export data to excel

gsea_fc_df_down <- as.data.frame(gsea_fc_down@result)
write.xlsx(gsea_fc_df_down, file = "GSEA_CC_results_down.xlsx")

gsea_fc_df_up <- as.data.frame(gsea_fc_up@result)
write.xlsx(gsea_fc_df_up, file = "GSEA_CC_results_up.xlsx")





