##########################################################################
#
#  script to perform SC analysis for dropseq data of mDA differentiation
#  of PINK1 vs CTRL cells
#
# 2024/10 by Corrado Ameli and Alexander Skupin (AS) - updated by AS 2025
#
##########################################################################

# ================================= LIBRARIES ==================================

library(Seurat)
library(dplyr)
library(tidyverse)
library(viridisLite)
library(viridis)
library(ggplot2)
library(openxlsx)
library(slingshot)


# the final object was generated by filtering for days and conditions from the full object:
#S_input = readRDS(file = '/Users/alexander.skupin/projects/papers_to_do/Michi_Pink1_differentiation/SC_Analysis/Michela_Transcriptomics_R/sc_analysis_pink1/SeuratFinal.rds')

#redset <- c("WT_57","WT_37" , "WT_18" , "WT_25" ,  "WT_0"   , "ND_37" ,  "ND_57"  , "ND_18" , "ND_25" ,  "ND_0")
#S_red = subset(S_input, ConditionDay %in% redset)
#unique(S_red$ConditionDay)
#saveRDS(S_red,paste("./SeuratFinal.rds",sep=""))




# ================================ PARAMETERS ==================================

# set your working directory accordingly
setwd('/Users/alexander.skupin/projects/teaching/WS2025/MADS/project1')


input_file = "./SeuratFinal.rds"
output_folder = "./Results/"

#to export things later
writeExcel = TRUE

# = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = 
#                             ---- RELABELING ----                  
# = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = 

# Load mapped data-sets

S = readRDS(input_file)

# Convert meta-data to factors

S$Day = factor(S$Day, levels = c(0,18,25,37,57))
S$Condition = str_replace_all(S$Condition, "ND","PINK1")
S$Condition = str_replace_all(S$Condition,"WT","CTL")
S$ConditionDay = paste(S$Condition,S$Day,sep = " ")

S$ConditionDay = factor(S$ConditionDay, levels = c("CTL 0","PINK1 0",
                                                   "CTL 18","PINK1 18",
                                                   "CTL 25","PINK1 25",
                                                   "CTL 37","PINK1 37",
                                                   "CTL 57","PINK1 57"))

S$ConditionDay = factor(S$ConditionDay, levels = c("CTL 0","CTL 18","CTL 25","CTL 37","CTL 57",
                                                   "PINK1 0","PINK1 18","PINK1 25","PINK1 37","PINK1 57"))

S$Condition = factor(S$Condition, levels = c("CTL","PINK1"))

# now you can have a look into the object ... summary, dim, head etc ...

#
Assays(S)
Layers(S)

# do we have already PCA information? 

FeaturePlot(S, features="nCount_RNA")
FeaturePlot(S, features="nCount_RNA",split.by='Day')
DimPlot(S, split.by='Day')

ElbowPlot(S,ndims = 30)

DimHeatmap(S, dims = 1:9, cells = 1000, balanced = TRUE)

######## new Dim reduction since the current is based on full data set

# if u run into memory issues - u can also put everything into S instead of S_new

S = ScaleData(S)
S = RunPCA(S,npcs = 50)

ElbowPlot(S,ndims = 30)
DimHeatmap(S, dims = 1:9, cells = 1000, balanced = TRUE)

# here u should play around with dims, n.neigbors check also ?RunUMAP - something for reduction=? ; what happens for other assays?
S = RunUMAP(S,dims = 1:100,assay = "integrated",n.neighbors = 30)

# We can store different parameter set in the object by defining reduction.name = "nameofreduction" -default is "umap"

DimPlot(object = S, reduction = "umap")
DimPlot(object = S, reduction = "umap", group.by = "Condition", split.by = "Day",shuffle = TRUE) 
DimPlot(object = S, reduction = "umap", group.by = "Day", split.by = "Condition",shuffle = TRUE) 


# = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = 
#                   ---- NORMALIZING ASSAYS BEFORE DEGs ----                  
# = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = 

S = NormalizeData(S,assay = "RNA")
S = NormalizeData(S,assay = "RNA_imputed")



# = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = 
#                            ---- DEGs DAYWISE ----                  
# = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = 
 









