

# ================================= LIBRARIES ==================================

library(Seurat)
library(dplyr)
library(tidyverse)
library(viridisLite)
library(viridis)
library(ggplot2)
library(openxlsx)
library(slingshot)



# the final object was generated by filtering for days and conditions from the full object:
#S_input = readRDS(file = '/Users/alexander.skupin/projects/papers_to_do/Michi_Pink1_differentiation/SC_Analysis/Michela_Transcriptomics_R/sc_analysis_pink1/SeuratFinal.rds')

#redset <- c("WT_57","WT_37" , "WT_18" , "WT_25" ,  "WT_0"   , "ND_37" ,  "ND_57"  , "ND_18" , "ND_25" ,  "ND_0")
#redset2 <- c("WT_57","WT_37" ,  "WT_0"   , "ND_37" ,  "ND_57"    ,  "ND_0")

#S_red = subset(S_input, ConditionDay %in% redset2)
#unique(S_red$ConditionDay)
#saveRDS(S_red,paste("./SeuratFinal_red.rds",sep=""))

# to get clean environment
rm(list = ls())


# ================================ PARAMETERS ==================================

# set your working directory accordingly
setwd('/Users/alexander.skupin/projects/teaching/WS2025/MADS/project1')

input_file = "./SeuratFinal.rds"
output_folder = "./Results/"

#to export things later
writeExcel = TRUE



# = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = 
#                             ---- RELABELING ----                  
# = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = 

# Load mapped data-sets

S = readRDS(input_file)

# summary(S)
# dim(S)
# head(colnames(S))
# tail(colnames(S))
# head(colnames(S))
# head(rownames(S))
# 
# head(S[[]])
# 
# Assays(S)


# Convert meta-data to factors

S$Day = factor(S$Day, levels = c(0,18,25,37,57))
S$Condition = str_replace_all(S$Condition, "ND","PINK1")
S$Condition = str_replace_all(S$Condition,"WT","CTL")
S$ConditionDay = paste(S$Condition,S$Day,sep = " ")

S$ConditionDay = factor(S$ConditionDay, levels = c("CTL 0","PINK1 0",
                                                   "CTL 18","PINK1 18",
                                                   "CTL 25","PINK1 25",
                                                   "CTL 37","PINK1 37",
                                                   "CTL 57","PINK1 57"))

S$ConditionDay = factor(S$ConditionDay, levels = c("CTL 0","CTL 18","CTL 25","CTL 37","CTL 57",
                                                   "PINK1 0","PINK1 18","PINK1 25","PINK1 37","PINK1 57"))

S$Condition = factor(S$Condition, levels = c("CTL","PINK1"))

# now you can have a look into the object ... summary, dim, head etc ...

## to get data in expression matrix

tempa <- subset(S, ConditionDay %in% "CTL 0")
expression_matrix_CTL_0 <- GetAssayData(tempa, slot = "data")

tempa <- subset(S, ConditionDay %in% "PINK1 0")
expression_matrix_PINK_0 <- GetAssayData(tempa, slot = "data")

###### useful package for correelation

# Install Hmisc package
#install.packages("Hmisc")

# Load the package
library(Hmisc)

#for control condition at day 0
rcorr_result_ctr_0 <- rcorr(t(as.matrix(expression_matrix_CTL_0)))
cor_matrix_ctr_0 <- rcorr_result_ctr_0$r
#for pink1 condition day 0
rcorr_result_pink_0 <- rcorr(t(as.matrix(expression_matrix_PINK_0)))
cor_matrix_pink_0 <- rcorr_result_pink_0$r


#replaces NaN with 0
cor_matrix_ctr_0[is.na(cor_matrix_ctr_0)] <- 0
cor_matrix_pink_0[is.na(cor_matrix_pink_0)] <- 0

hist(cor_matrix_ctr_0,breaks=200)
hist(cor_matrix_pink_0,breaks=200)

heatmap(cor_matrix_ctr_0, na.rm=T,
        col = colorRampPalette(c("blue", "white", "red"))(50),
        scale = "none")

#wihtout clustering
heatmap(cor_matrix_ctr_0, na.rm=T, Rowv = NA, Colv = NA,
        col = colorRampPalette(c("blue", "white", "red"))(50),
        scale = "none")

heatmap(cor_matrix_pink_0, na.rm=T, Rowv = NA, Colv = NA,
        col = colorRampPalette(c("blue", "white", "red"))(50),
        scale = "none")

# more fancy tool  
#install.packages("ComplexHeatmap")
#install.packages("circlize")
library(ComplexHeatmap)
library(circlize)

Heatmap(cor_matrix_ctr_0, 
        name = "Correlation", 
        col = colorRamp2(c(-1, 0, 1), c("blue", "white", "red")))

# no names and clustering
Heatmap(cor_matrix_ctr_0, 
        name = "Correlation", cluster_rows = FALSE, cluster_columns = FALSE, 
        show_row_names = FALSE, show_column_names = FALSE,
        col = colorRamp2(c(-1, 0, 1), c("blue", "white", "red")))

Heatmap(cor_matrix_pink_0, 
        name = "Correlation", cluster_rows = FALSE, cluster_columns = FALSE, 
        show_row_names = FALSE, show_column_names = FALSE,
        col = colorRamp2(c(-1, 0, 1), c("blue", "white", "red")))

# to reduce correlation matrix by identifying rows and columns with at least one correlation > cthresh
# play with treshhold
ctresh <- 0.6
# for filtering have to set trivial diagonal to 0
diag(cor_matrix_ctr_0) <- 0
rows_to_keep_ctr_0 <- apply(cor_matrix_ctr_0, 1, function(row) any(abs(row) > ctresh))
cols_to_keep_ctr_0 <- apply(cor_matrix_ctr_0, 2, function(col) any(abs(col) > ctresh))

diag(cor_matrix_pink_0) <- 0
rows_to_keep_pink_0 <- apply(cor_matrix_pink_0, 1, function(row) any(abs(row) > ctresh))
cols_to_keep_pink_0 <- apply(cor_matrix_pink_0, 2, function(col) any(abs(col) > ctresh))

# Subset the correlation matrix
reduced_cor_matrix_ctr_0 <- cor_matrix_ctr_0[rows_to_keep_ctr_0, cols_to_keep_ctr_0]
reduced_cor_matrix_pink_0 <- cor_matrix_pink_0[rows_to_keep_pink_0, cols_to_keep_pink_0]

Heatmap(reduced_cor_matrix_ctr_0, 
        name = "Correlation", cluster_rows = FALSE, cluster_columns = FALSE, 
        show_row_names = FALSE, show_column_names = FALSE,
        col = colorRamp2(c(-1, 0, 1), c("blue", "white", "red")))


heatmap(reduced_cor_matrix_ctr_0, na.rm=T, Rowv = NA, Colv = NA,
        col = colorRampPalette(c("blue", "white", "red"))(50),
        scale = "none")

heatmap(reduced_cor_matrix_pink_0, na.rm=T, Rowv = NA, Colv = NA,
        col = colorRampPalette(c("blue", "white", "red"))(50),
        scale = "none")

dim(reduced_cor_matrix_ctr_0)
dim(reduced_cor_matrix_pink_0)
# to put things to 0 that are not higher than a treshhold ctresh_2

ctresh_2 = 0.6
#for CTRL condition
filtered_cor_matrix_ctr_0 <- ifelse(abs(reduced_cor_matrix_ctr_0) >= ctresh_2, reduced_cor_matrix_ctr_0, 0)

heatmap(filtered_cor_matrix_ctr_0, na.rm=T, Rowv = NA, Colv = NA,
        col = colorRampPalette(c("blue", "white", "red"))(50),
        scale = "none")

dim(filtered_cor_matrix_ctr_0 )

#for PINK1 condition
filtered_cor_matrix_pink_0 <- ifelse(abs(reduced_cor_matrix_pink_0) >= ctresh_2, reduced_cor_matrix_pink_0, 0)

heatmap(filtered_cor_matrix_pink_0, na.rm=T, Rowv = NA, Colv = NA,
        col = colorRampPalette(c("blue", "white", "red"))(50),
        scale = "none")

dim(filtered_cor_matrix_pink_0 )

# adjacency matrix 
#ctr
adj_matrix_ctr_0 <- ifelse(abs(reduced_cor_matrix_ctr_0) > ctresh, 1, 0) #how to break this down into pos and negative
diag(adj_matrix_ctr_0) <- 0

heatmap(adj_matrix_ctr_0, na.rm=T, Rowv = NA, Colv = NA,
        col = colorRampPalette(c("white", "black"))(3),
        scale = "none")

nodes_ctr_0 <-  rowSums(adj_matrix_ctr_0)
hist(nodes_ctr_0, breaks=100)

# get genenames of subset
sas <- names(adj_matrix_ctr_0[rowSums(adj_matrix_ctr_0)>10 & rowSums(adj_matrix_ctr_0)<100,1])

#pink1
adj_matrix_pink_0 <- ifelse(abs(reduced_cor_matrix_pink_0) > ctresh, 1, 0) #how to break this down into pos and negative
diag(adj_matrix_pink_0) <- 0

heatmap(adj_matrix_pink_0, na.rm=T, Rowv = NA, Colv = NA,
        col = colorRampPalette(c("white", "black"))(3),
        scale = "none")

nodes_pink_0 <-  rowSums(adj_matrix_pink_0)
hist(nodes_pink_0, breaks=100)


# for some network representation

# install.packages("igraph")
library(igraph)
# ctr
network_graph_ctr_0 <- graph_from_adjacency_matrix(adj_matrix_ctr_0, mode = "undirected")

plot(network_graph_ctr_0, 
     vertex.size = 5,        # Size of nodes
     vertex.label.cex = 0.5,  # Font size for labels
     vertex.label.color = "black",  # Label color
     edge.width = 2,          # Width of edges
     edge.color = "gray")     # Color of edges


V(network_graph_ctr_0)$color <- c(colorRampPalette(c("black", "grey", "orange", "red"))(dim(adj_matrix_ctr_0)[1]))
E(network_graph_ctr_0)$width <- 2

plot(network_graph_ctr_0,
     vertex.size = 5,        # Size of nodes
     vertex.label.cex = .6,  # Font size for labels
     vertex.label.color = "black",  # Label color
     edge.width = 4,          # Width of edges
     edge.color = "gray"
     )

# pink
network_graph_pink_0 <- graph_from_adjacency_matrix(adj_matrix_pink_0, mode = "undirected")

plot(network_graph_pink_0, 
     vertex.size = 5,        # Size of nodes
     vertex.label.cex = 0.5,  # Font size for labels
     vertex.label.color = "black",  # Label color
     edge.width = 2,          # Width of edges
     edge.color = "gray")     # Color of edges


V(network_graph_pink_0)$color <- c(colorRampPalette(c("black", "grey", "orange", "red"))(dim(adj_matrix_pink_0)[1]))
E(network_graph_pink_0)$width <- 2

plot(network_graph_pink_0,
     vertex.size = 5,        # Size of nodes
     vertex.label.cex = .6,  # Font size for labels
     vertex.label.color = "black",  # Label color
     edge.width = 4,          # Width of edges
     edge.color = "gray"
)


layout(matrix(c(1, 2), nrow = 1, ncol = 2, byrow = TRUE))

# reduce adjacency matrix to only highly connected nodes
ntres = 5
nodes_to_keep_ctr_0 <- which(nodes_ctr_0 >= ntres)
red_adj_matrix_ctr_0 <- adj_matrix_ctr_0[nodes_to_keep_ctr_0, nodes_to_keep_ctr_0]

nodes_to_keep_pink_0 <- which(nodes_pink_0 >= ntres)
red_adj_matrix_pink_0 <- adj_matrix_pink_0[nodes_to_keep_pink_0, nodes_to_keep_pink_0]


heatmap(red_adj_matrix_ctr_0, na.rm=T, Rowv = NA, Colv = NA,
        col = colorRampPalette(c("white", "black"))(3),
        scale = "none")

heatmap(red_adj_matrix_pink_0, na.rm=T, Rowv = NA, Colv = NA,
        col = colorRampPalette(c("white", "black"))(3),
        scale = "none")

# for network representation

#ctr
red_network_graph_ctr_0 <- graph_from_adjacency_matrix(red_adj_matrix_ctr_0, mode = "undirected")

plot(red_network_graph_ctr_0, 
     vertex.size = 5,        # Size of nodes
     vertex.label.cex = 0.5,  # Font size for labels
     vertex.label.color = "black",  # Label color
     edge.width = 2,          # Width of edges
     edge.color = "gray")     # Color of edges

#pink1
red_network_graph_pink_0 <- graph_from_adjacency_matrix(red_adj_matrix_pink_0, mode = "undirected")

plot(red_network_graph_pink_0, 
     vertex.size = 5,        # Size of nodes
     vertex.label.cex = 0.5,  # Font size for labels
     vertex.label.color = "black",  # Label color
     edge.width = 2,          # Width of edges
     edge.color = "gray")     # Color of edges


# to compare condition by adjacency pattern

# Subset the correlation matrix
com_ind_0 <- c(which(rows_to_keep_ctr_0),which(rows_to_keep_pink_0)) 
shared_red_cor_matrix_ctr_0 <- cor_matrix_ctr_0[com_ind_0, com_ind_0  ]
shared_red_cor_matrix_pink_0 <- cor_matrix_pink_0[com_ind_0, com_ind_0  ]


h1 <- Heatmap(shared_red_cor_matrix_ctr_0, border=T,
        name = "Correlation", cluster_rows = FALSE, cluster_columns = FALSE, 
        show_row_names = FALSE, show_column_names = FALSE,
        col = colorRamp2(c(-1, 0, 1), c("blue", "white", "red")))

h2 <- Heatmap(shared_red_cor_matrix_pink_0,  border=T,
              name = "Correlation", cluster_rows = FALSE, cluster_columns = FALSE, 
              show_row_names = FALSE, show_column_names = FALSE,
              col = colorRamp2(c(-1, 0, 1), c("blue", "white", "red")))


draw(h1 + h2)

# for common adjacency as above

com_adj_matrix_ctr_0 <- ifelse(abs(shared_red_cor_matrix_ctr_0) > ctresh, 1, 0) #how to break this down into pos and negative
diag(com_adj_matrix_ctr_0) <- 0

heatmap(com_adj_matrix_ctr_0, na.rm=T, Rowv = NA, Colv = NA,
        col = colorRampPalette(c("white", "black"))(3),
        scale = "none")

#pink1
com_adj_matrix_pink_0 <- ifelse(abs(shared_red_cor_matrix_pink_0) > ctresh, 1, 0) #how to break this down into pos and negative
diag(com_adj_matrix_pink_0) <- 0

heatmap(com_adj_matrix_pink_0, na.rm=T, Rowv = NA, Colv = NA,
        col = colorRampPalette(c("white", "black"))(3),
        scale = "none")


h3 <- Heatmap(com_adj_matrix_ctr_0,  border=T,
              name = "Adjacency CTR", cluster_rows = FALSE, cluster_columns = FALSE, 
              show_row_names = FALSE, show_column_names = FALSE,
              col = colorRamp2(c( 0, 1), c( "white", "black")))

h4 <- Heatmap(com_adj_matrix_pink_0,  border=T,
              name = "Adjecency PINK1", cluster_rows = FALSE, cluster_columns = FALSE, 
              show_row_names = FALSE, show_column_names = FALSE,
              col = colorRamp2(c(0, 1), c( "white", "black")))


draw(h3 + h4)

# can be done for other time points - separate?


##### for big correlation calculations:

# Install gputools package
#install.packages("gputools")

# Load the package
#library(gputools)

# Compute correlation matrix
#cor_matrix <- gpuCor(data_matrix, method = "pearson")

# or alternative
# Install package
install.packages("bigstatsr")
# Load the package
library(bigstatsr)
# to use binary format
cm_0_c <- as_FBM(as.matrix(expression_matrix_CTL_0)) # binary expression matrix for cell correlations
cor_matrix_cells <- big_cor(cm_0_c) # correlation for cells


########## For String analysis

degs <- read.xlsx('./Results/DEG_DETAILED_MADS_new_RNA.xlsx')

degs_0_all <- degs[degs$Day==0,]

degs_0 <- degs_0_all[abs(degs_0_all$avg_log2FC)>1,1] 


#this csv file can be then uploaded into string 
write_csv(as.data.frame(degs_0), file='./degs_day0.csv')
